const codeTheme = {
  'code[class*="language-"]': {
    color: '#fff',
    background: 'none',
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    fontSize: '13px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    tabSize: '4',
    hyphens: 'none'
  },
  'pre[class*="language-"]': {
    color: '#fff',
    background: 'none',
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    fontSize: '13px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    tabSize: '4',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
    borderRadius: '0.3em'
  },
  comment: { color: '#636e7b' },
  prolog: { color: '#636e7b' },
  doctype: { color: '#636e7b' },
  cdata: { color: '#636e7b' },
  punctuation: { color: '#8b949e' },
  property: { color: '#79c0ff' },
  tag: { color: '#7ee787' },
  boolean: { color: '#ff7b72' },
  number: { color: '#ff7b72' },
  constant: { color: '#79c0ff' },
  symbol: { color: '#79c0ff' },
  deleted: { color: '#ffa657' },
  selector: { color: '#d2a8ff' },
  'attr-name': { color: '#79c0ff' },
  string: { color: '#a5d6ff' },
  char: { color: '#a5d6ff' },
  builtin: { color: '#79c0ff' },
  inserted: { color: '#7ee787' },
  operator: { color: '#ff7b72' },
  entity: { color: '#79c0ff', cursor: 'help' },
  url: { color: '#79c0ff' },
  '.language-css .token.string': { color: '#a5d6ff' },
  '.style .token.string': { color: '#a5d6ff' },
  variable: { color: '#ffa657' },
  atrule: { color: '#ff7b72' },
  'attr-value': { color: '#a5d6ff' },
  function: { color: '#d2a8ff' },
  keyword: { color: '#ff7b72' },
  regex: { color: '#a5d6ff' },
  important: { color: '#ff7b72', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' }
};

export default codeTheme;
